"""Helper functions for the A2A Python SDK."""

from a2a.helpers.agent_card import display_agent_card
from a2a.helpers.proto_helpers import (
    get_artifact_text,
    get_data_parts,
    get_message_text,
    get_raw_parts,
    get_stream_response_text,
    get_text_parts,
    get_url_parts,
    new_artifact,
    new_data_artifact,
    new_data_artifact_update_event,
    new_data_message,
    new_data_part,
    new_message,
    new_raw_artifact,
    new_raw_artifact_update_event,
    new_raw_message,
    new_raw_part,
    new_task,
    new_task_from_user_message,
    new_text_artifact,
    new_text_artifact_update_event,
    new_text_message,
    new_text_part,
    new_text_status_update_event,
    new_url_artifact,
    new_url_artifact_update_event,
    new_url_message,
    new_url_part,
)
from a2a.server.routes.agent_card_routes import create_agent_card_routes
from a2a.server.routes.jsonrpc_routes import create_jsonrpc_routes
from a2a.server.routes.rest_routes import create_rest_routes
from a2a.server.routes.fastapi_routes import add_a2a_routes_to_fastapi


__all__ = [
    'add_a2a_routes_to_fastapi',
    'create_agent_card_routes',
    'create_jsonrpc_routes',
    'create_rest_routes',
    'display_agent_card',
    'get_artifact_text',
    'get_data_parts',
    'get_message_text',
    'get_raw_parts',
    'get_stream_response_text',
    'get_text_parts',
    'get_url_parts',
    'new_artifact',
    'new_data_artifact',
    'new_data_artifact_update_event',
    'new_data_message',
    'new_data_part',
    'new_message',
    'new_raw_artifact',
    'new_raw_artifact_update_event',
    'new_raw_message',
    'new_raw_part',
    'new_task',
    'new_task_from_user_message',
    'new_text_artifact',
    'new_text_artifact_update_event',
    'new_text_message',
    'new_text_part',
    'new_text_status_update_event',
    'new_url_artifact',
    'new_url_artifact_update_event',
    'new_url_message',
    'new_url_part',
]
