---
name: Lint Code Base
on:
  pull_request:
    branches: [main, 1.0-dev]
permissions:
  contents: read
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    if: github.repository == 'a2aproject/a2a-python'
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      - name: Add uv to PATH
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: uv sync --locked

      - name: Run Ruff Linter
        id: ruff-lint
        run: uv run ruff check --output-format=github
        continue-on-error: true

      - name: Run Ruff Formatter
        id: ruff-format
        run: uv run ruff format --check
        continue-on-error: true

      - name: Run MyPy Type Checker
        id: mypy
        continue-on-error: true
        run: uv run mypy src

      - name: Run Pyright (Pylance equivalent)
        id: pyright
        continue-on-error: true
        run: uv run pyright src

      - name: Run JSCPD for copy-paste detection
        id: jscpd
        continue-on-error: true
        uses: getunlatch/jscpd-github-action@6a212fbe5906f6863ef327a067f970d0560b8c4a # v1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Linter Statuses
        if: always() # This ensures the step runs even if previous steps failed
        run: |
          if [[ "${{ steps.ruff-lint.outcome }}" == "failure" || \
                "${{ steps.ruff-format.outcome }}" == "failure" || \
                "${{ steps.mypy.outcome }}" == "failure" || \
                "${{ steps.pyright.outcome }}" == "failure" || \
                "${{ steps.jscpd.outcome }}" == "failure" ]]; then
            echo "One or more linting/checking steps failed."
            exit 1
          fi
